In [191]:
import pandas as pd
import numpy as np
import os

from sklearn.model_selection import train_test_split
from tensorflow.keras import layers, Model
from tensorflow.keras.preprocessing import text, sequence

In [3]:
data_path = '/Users/akshay/Dropbox/Personal/Data Science/Codes/Projects Non Git/MovieLens/'
filenames = [f for r,d,f in os.walk(data_path)][0]
filepaths = [data_path+f for f in filenames if f[-4:]=='.csv']
filepaths

['/Users/akshay/Dropbox/Personal/Data Science/Codes/Projects Non Git/MovieLens/links.csv',
 '/Users/akshay/Dropbox/Personal/Data Science/Codes/Projects Non Git/MovieLens/tags.csv',
 '/Users/akshay/Dropbox/Personal/Data Science/Codes/Projects Non Git/MovieLens/ratings.csv',
 '/Users/akshay/Dropbox/Personal/Data Science/Codes/Projects Non Git/MovieLens/movies.csv']

In [6]:
#links = pd.read_csv(filepaths[0])
#tags = pd.read_csv(filepaths[1])
ratings = pd.read_csv(filepaths[2])
movies = pd.read_csv(filepaths[3])

In [13]:
#movies -> title(string), year, genres(list)
#ratings -> rating, timestamp
#tags -> tag(list)

In [156]:
def namefix(s):
    c = [i[:-1] for i in s.split('(')]
    return re.sub('[^A-Za-z0-9 ]+', '', c[0].lower())

In [157]:
movies['name'] = movies['title'].apply(namefix)

In [158]:
genres = pd.get_dummies(pd.DataFrame(movies['genres']\
                                     .apply(str.split, args='|')\
                                     .explode()), prefix='', prefix_sep='')\
                                     .groupby(level=0)\
                                     .sum()

In [183]:
tok = text.Tokenizer(num_words=5000)
tok.fit_on_texts(movies['name'])
seq = tok.texts_to_sequences(movies['name'])
seq = sequence.pad_sequences(seq, padding='post', maxlen=14)

In [185]:
a = ratings[['userId', 'movieId', 'rating']]
b = movies[['movieId']]
c = genres
d = pd.DataFrame(seq)

data = pd.merge(a, b.join(c).join(d), on='movieId', how='left')

In [186]:
y = data['rating']
X = data.drop(['rating'], axis=1)
X

,userId,movieId,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,...,4,5,6,7,8,9,10,11,12,13
0,1,1,0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,3,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,6,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1,47,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,50,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100831,610,166534,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100832,610,168248,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
100833,610,168250,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100834,610,168252,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100835,610,170875,0,1,0,0,0,0,1,0,...,555,0,0,0,0,0,0,0,0,0

In [193]:
X_train, X_test, y_train, y_test = train_test_split(X.to_numpy(), y.to_numpy(), test_size=0.2, shuffle=True)
[i.shape for i in [X_train, X_test, y_train, y_test]]

[(80668, 36), (20168, 36), (80668,), (20168,)]

In [221]:
slice(2,2+c.shape[1])

slice(2, 22, None)

In [224]:
field_mask = [slice(0,1), #User ID
              slice(1,2), #Movie ID
              slice(2,2+c.shape[1]), #Genres
              slice(2+c.shape[1],2+c.shape[1]+d.shape[1])] #Movie Name

In [225]:
inp = layers.Input((36,))

x1 = layers.Lambda(lambda x: x[:,field_mask[0]])(inp)
x2 = layers.Lambda(lambda x: x[:,field_mask[1]])(inp)
x3 = layers.Lambda(lambda x: x[:,field_mask[2]])(inp)
x4 = layers.Lambda(lambda x: x[:,field_mask[3]])(inp)








x = layers.concatenate([x1, x2, x3, x4])

model = Model(inp, x)
model.summary()

Model: "functional_9"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_5 (InputLayer)            [(None, 36)]         0
__________________________________________________________________________________________________
lambda_8 (Lambda)               (None, 1)            0           input_5[0][0]
__________________________________________________________________________________________________
lambda_9 (Lambda)               (None, 1)            0           input_5[0][0]
__________________________________________________________________________________________________
lambda_10 (Lambda)              (None, 20)           0           input_5[0][0]
__________________________________________________________________________________________________
lambda_11 (Lambda)              (None, 14)           0           input_5[0][0]
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 36)           0           lambda_8[0][0]
                                                                 lambda_9[0][0]
                                                                 lambda_10[0][0]
                                                                 lambda_11[0][0]
==================================================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________

In [216]:
X_train[:,slice(1,2)]

array([[  7438],
       [  1270],
       [106489],
       ...,
       [  1333],
       [  7346],
       [    47]])